<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatIngresosGastosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cat_ingresos_gastos')->insert([
            ['codigo' => "610-1-0-0",	 'descripcion' => "VENTA UNIDADES MENUDEO E INTERCAMBIO"],
            ['codigo' => "610-3-0-0",	 'descripcion' => "VENTA DE SICREA"],
            ['codigo' => "610-11-0-0",	'descripcion' =>  "VENTA DE ACCESORIOS"],
            ['codigo' => "610-6-0-0",	 'descripcion' => "VENTAS SONI AUTOMOTRIZ SUCURSAL"],
            ['codigo' => "650-1-0-0",	 'descripcion' => "DEV. Y BONIF. S/VTAS. MENUDEO"],
            ['codigo' => "650-3-0-0",	 'descripcion' => "DEV. Y BONIF. S/VTAS. SICREA"],
            ['codigo' => "610-2-0-0",	 'descripcion' => "VENTA DE FLOTILLAS"],
            ['codigo' => "650-2-0-0",	 'descripcion' => "DEV. Y BONIF. S/VTAS. FLOTILLAS"],
            ['codigo' => "610-5-0-0",	 'descripcion' => "VENTA DE UNIDADES INTERCAMBIOS"],
            ['codigo' => "610-10-0-0",	'descripcion' =>  "VENTA DE UNIDADES USADAS"],
            ['codigo' => "650-5-0-0",	 'descripcion' => "DEV. Y BONIF. S/VTAS. AUTOS USADOS"],
            ['codigo' => "610-12-0-0",	'descripcion' =>  "VENTA SERVICIO"],
            ['codigo' => "610-14-0-0",	'descripcion' =>  "VENTA HOJALATERIA Y PINTURA"],
            ['codigo' => "610-13-1-0",	'descripcion' =>  "VENTA DE REFACCIONES"],
            ['codigo' => "610-15-0-0",	'descripcion' =>  "T.O.T."],
            ['codigo' => "650-6-0-0",	 'descripcion' => "DEV. Y BONIF. S/VTAS. SERVICIO"],
            ['codigo' => "610-13-2-0",	'descripcion' =>  "VENTA DE REFACCIONES"],
            ['codigo' => "650-7-0-0",	 'descripcion' => "DEV. Y BONIF. S/VTAS. REFACCIONES"],
            ['codigo' => "610-16-1-0",	'descripcion' =>  "OTROS INGRESOS  C/iva"],
            ['codigo' => "610-16-2-0",	'descripcion' =>  "OTROS INGRESOS  S/IVA"],
            ['codigo' => "610-16-3-0",	'descripcion' =>  "INCENTIVOS VEHICULOS"],
            ['codigo' => "610-16-5-0",	'descripcion' =>  "ALTIMA"],
            ['codigo' => "610-16-11-0",'descripcion' => 	 "NP 300"],
            ['codigo' => "610-16-61-0",'descripcion' => 	 "PRODUCTOS Y GASTOS FINANCIEROS"],
            ['codigo' => "610-16-69-0",'descripcion' => 	 "INTERESES GANADOS"],
            ['codigo' => "710-1-0-0",	 'descripcion' => "COSTO UNIDADES MENUDEO E INTERCAMBIO"],
            ['codigo' => "710-2-0-0",	 'descripcion' => "COSTO DE FLOTILLAS"],
            ['codigo' => "710-3-0-0",	 'descripcion' => "COSTO DE SICREA"],
            ['codigo' => "710-5-0-0",	 'descripcion' => "COSTO UNIDADES INTERCAMBIOS"],
            ['codigo' => "710-6-0-0",	 'descripcion' => "COSTO DE VENTAS SONI AUTOMOTRIZ SUCURSAL"],
            ['codigo' => "710-9-0-0",	 'descripcion' => "COSTO DE PREVIAS"],
            ['codigo' => "710-10-0-0",	'descripcion' =>  "COSTO DE AUTOS USADOS"],
            ['codigo' => "710-11-0-0",	'descripcion' =>  "COSTO DE ACCESORIOS"],
            ['codigo' => "710-12-0-0",	'descripcion' =>  "COSTO SERVICIO"],
            ['codigo' => "710-13-1-0",	'descripcion' =>  "COSTO REFACCIONES SERVICIO"],
            ['codigo' => "710-13-2-0",	'descripcion' =>  "COSTO REFACCIONES REFACCIONES"],
            ['codigo' => "710-14-0-0",	'descripcion' =>  "COSTO HOJALATERIA Y PINTURA"],
            ['codigo' => "710-15-0-0",	'descripcion' =>  "COSTO TRABAJO OTROS TALLERES"],
            ['codigo' => "710-16-0-0",	'descripcion' =>  "COSTO DE FINANC."],
            ['codigo' => "710-17-0-0",	'descripcion' =>  "COSTO DE VENTA DE ACTIVO FIJO"],
            ['codigo' => "710-21-0-0",	'descripcion' =>  "COSTO DE VENTA OTROS"],
            ['codigo' => "810-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "810-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "810-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "810-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "810-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "810-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "810-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "810-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "810-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "810-10-0-0",	'descripcion' =>  "CREDITO AL SALARIO"],
            ['codigo' => "810-11-0-0",	'descripcion' =>  "IMPUESTO SUSTITUTIVO"],
            ['codigo' => "810-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "810-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "810-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "810-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "810-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "810-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "810-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "810-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "810-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "810-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "810-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "810-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "810-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "810-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "810-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "810-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "810-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "810-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "810-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "810-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "810-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "810-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "810-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "810-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "810-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "810-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "810-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "810-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "810-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "810-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "810-43-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "810-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "810-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "810-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "810-49-0-0",	'descripcion' =>  "BASES PARA CONCURSOS"],
            ['codigo' => "810-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "810-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "810-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "810-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "810-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "810-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "810-56-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "810-57-0-0",	'descripcion' =>  "MEDIACION MERCANTIL"],
            ['codigo' => "810-58-0-0",	'descripcion' =>  "PRIMA DOMINICAL"],
            ['codigo' => "810-59-0-0",	'descripcion' =>  "SEPTIMO DIA"],
            ['codigo' => "810-60-0-0",	'descripcion' =>  "DIA FESTIVO"],
            ['codigo' => "810-61-0-0",	'descripcion' =>  "HORAS EXTRAS"],
            ['codigo' => "810-62-0-0",	'descripcion' =>  "MULTAS Y PENALIZACIONES"],
            ['codigo' => "810-63-0-0",	'descripcion' =>  "GESTORIAS  "],
            ['codigo' => "810-64-0-0",	'descripcion' =>  "SERVICIOS A UNIDADES"],
            ['codigo' => "810-66-0-0",	'descripcion' =>  "RENTA DE AUTOSYSTEM"],
            ['codigo' => "810-68-0-0",	'descripcion' =>  "VERIFICACIONES"],
            ['codigo' => "810-69-0-0",	'descripcion' =>  "OTROS SERVICIOS"],
            ['codigo' => "810-70-0-0",	'descripcion' =>  "ASIMILADOS A SALARIO"],
            ['codigo' => "810-71-0-0",	'descripcion' =>  "UNIFORMES"],
            ['codigo' => "810-86-0-0",	'descripcion' =>  "OTROS SERVICIOS"],
            ['codigo' => "811-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "811-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "811-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "811-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "811-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "811-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "811-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "811-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "811-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "811-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "811-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "811-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "811-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "811-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "811-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "811-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "811-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "811-20-0-0",	'descripcion' =>  "HONORARIOS PROFESIONALES"],
            ['codigo' => "811-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "811-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "811-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "811-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "811-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "811-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "811-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "811-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "811-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "811-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "811-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "811-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "811-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "811-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "811-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "811-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "811-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "811-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "811-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "811-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "811-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "811-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "811-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "811-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "811-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "811-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "811-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "811-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "811-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "811-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "811-59-0-0",	'descripcion' =>  ""],
            ['codigo' => "811-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "812-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "812-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "812-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "812-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "812-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "812-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "812-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "812-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "812-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "812-10-0-0",	'descripcion' =>  "CREDITO AL SALARIO"],
            ['codigo' => "812-11-0-0",	'descripcion' =>  "IMPUESTO SUSTITUTIVO"],
            ['codigo' => "812-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "812-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "812-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "812-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "812-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "812-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "812-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "812-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "812-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "812-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "812-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "812-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "812-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "812-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "812-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "812-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "812-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "812-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "812-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "812-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "812-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "812-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "812-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "812-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "812-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "812-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "812-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "812-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "812-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "812-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "812-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "812-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "812-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "812-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "812-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "812-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "812-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "812-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "812-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "812-59-0-0",	'descripcion' =>  ""],
            ['codigo' => "812-56-0-0",	'descripcion' =>  "CAFETERIA"],
            ['codigo' => "814-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "814-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "814-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "814-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "814-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "814-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "814-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "814-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "814-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "814-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "814-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "814-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "814-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "814-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "814-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "814-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "814-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "814-20-0-0",	'descripcion' =>  "HONORARIOS PROFESIONALES"],
            ['codigo' => "814-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "814-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "814-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "814-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "814-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "814-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "814-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "814-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "814-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "814-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "814-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "814-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "814-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "814-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "814-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "814-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "814-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "814-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "814-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "814-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "814-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "814-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "814-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "814-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "814-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "814-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "814-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "814-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "814-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "814-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "814-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "814-57-0-0",	'descripcion' =>  "MULTAS Y PENALIZACIONES"],
            ['codigo' => "814-59-0-0",	'descripcion' =>  "uniforMES"],
            ['codigo' => "814-56-0-0",	'descripcion' =>  "CAFETERIA"],
            ['codigo' => "814-66-0-0",	'descripcion' =>  "RENTA DE AUTOSYSTEM"],
            ['codigo' => "815-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "815-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS"],
            ['codigo' => "815-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "815-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "815-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "815-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA DE ANTIGUEDAD"],
            ['codigo' => "815-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "815-9-0-0",	 'descripcion' => "GASTOS DE FIN DE AÑO"],
            ['codigo' => "815-12-0-0",	'descripcion' =>  "2% SOBRE NOMINA"],
            ['codigo' => "815-13-0-0",	'descripcion' =>  "5% INFONAVIT"],
            ['codigo' => "815-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "815-15-0-0",	'descripcion' =>  "SAR"],
            ['codigo' => "815-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESRITORIO"],
            ['codigo' => "815-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "815-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "815-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "815-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "815-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "815-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQ. DE TRANSPORTE"],
            ['codigo' => "815-23-0-0",	'descripcion' =>  "MANTENIMIENTO DE EDIFICIO Y EQUIPO"],
            ['codigo' => "815-24-0-0",	'descripcion' =>  "TELEFONO TELEGRAFO Y CORREO"],
            ['codigo' => "815-25-0-0",	'descripcion' =>  "LUZ AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "815-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "815-29-0-0",	'descripcion' =>  "DREPRECIACION DE EDIFICIO"],
            ['codigo' => "815-30-0-0",	'descripcion' =>  "DEPREC. DE MAQ Y EQ. DE TALLER"],
            ['codigo' => "815-31-0-0",	'descripcion' =>  "DEP. DE EQUIPO DE TRANSPORTE"],
            ['codigo' => "815-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "815-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "815-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "815-36-0-0",	'descripcion' =>  "FLETES EMBARQUES Y ACARREOS"],
            ['codigo' => "815-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "815-39-0-0",	'descripcion' =>  "COMISIONES BANACARIAS"],
            ['codigo' => "815-42-0-0",	'descripcion' =>  "REACONSICIONAMIENTO DE UNIDADES"],
            ['codigo' => "815-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE OFICINA Y COMPUTO"],
            ['codigo' => "815-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "815-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "815-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "815-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "815-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "815-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "820-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "820-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "820-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "820-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "820-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "820-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "820-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "820-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "820-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "820-10-0-0",	'descripcion' =>  "CREDITO AL SALARIO"],
            ['codigo' => "820-11-0-0",	'descripcion' =>  "IMPUESTO SUSTITUTIVO"],
            ['codigo' => "820-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "820-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "820-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "820-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "820-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "820-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "820-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "820-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "820-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "820-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "820-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "820-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "820-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "820-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "820-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "820-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "820-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "820-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "820-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "820-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "820-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "820-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "820-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "820-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "820-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "820-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "820-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "820-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "820-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "820-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "820-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "820-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "820-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "820-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "820-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "820-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "820-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "820-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "820-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "820-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "820-56-0-0",	'descripcion' =>  "CAFETERIA"],
            ['codigo' => "820-59-0-0",	'descripcion' =>  "UNIFORMES DE TRABAJO"],
            ['codigo' => "820-66-0-0",	'descripcion' =>  "RENTA DE AUTOSYSTEM"],
            ['codigo' => "820-70-0-0",	'descripcion' =>  "ASIMILADOS A SALARIO"],
            ['codigo' => "830-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "830-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "830-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "830-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "830-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "830-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "830-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "830-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "830-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "830-10-0-0",	'descripcion' =>  "CREDITO AL SALARIO"],
            ['codigo' => "830-11-0-0",	'descripcion' =>  "IMPUESTO SUSTITUTIVO"],
            ['codigo' => "830-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "830-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "830-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "830-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "830-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "830-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "830-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "830-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "830-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "830-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "830-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "830-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "830-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "830-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "830-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "830-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "830-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "830-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "830-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "830-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "830-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "830-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "830-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "830-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "830-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "830-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "830-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "830-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "830-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "830-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "830-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "830-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "830-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "830-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "830-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "830-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "830-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "830-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "830-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "830-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "830-56-0-0",	'descripcion' =>  "CAFETERIA"],
            ['codigo' => "830-57-0-0",	'descripcion' =>  "MEDIACION MERCANTIL"],
            ['codigo' => "830-59-0-0",	'descripcion' =>  "UNIFORMES"],
            ['codigo' => "830-63-0-0",	'descripcion' =>  "GESTORIAS"],
            ['codigo' => "830-64-0-0",	'descripcion' =>  "SERVICIOS A UNIDADES"],
            ['codigo' => "830-65-0-0",	'descripcion' =>  "RECARGOS"],
            ['codigo' => "830-62-0-0",	'descripcion' =>  "MULTAS"],
            ['codigo' => "830-70-0-0",	'descripcion' =>  "ASIMILADOS A SALARIO"],
            ['codigo' => "840-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "840-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "840-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS."],
            ['codigo' => "840-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "840-5-0-0",	 'descripcion' => "GRATIF. Y COMPENSACIONES"],
            ['codigo' => "840-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "840-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA ANTIGUEDAD"],
            ['codigo' => "840-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "840-9-0-0",	 'descripcion' => "GASTOS DE FIN DE A¥O"],
            ['codigo' => "840-10-0-0",	'descripcion' =>  "CREDITO AL SALARIO"],
            ['codigo' => "840-11-0-0",	'descripcion' =>  "IMPUESTO SUSTITUTIVO"],
            ['codigo' => "840-12-0-0",	'descripcion' =>  "2 % SOBRE NOMINAS"],
            ['codigo' => "840-13-0-0",	'descripcion' =>  "5 % I.N.F.O.N.A.V.I.T."],
            ['codigo' => "840-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "840-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "840-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "840-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "840-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "840-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "840-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "840-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "840-22-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE TRANSPORTE"],
            ['codigo' => "840-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "840-24-0-0",	'descripcion' =>  "TELEFONO,TELEG, Y CORREO"],
            ['codigo' => "840-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "840-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "840-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "840-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "840-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "840-30-0-0",	'descripcion' =>  "DEPREC.DE MAQ.Y EQ.DE TALLER"],
            ['codigo' => "840-31-0-0",	'descripcion' =>  "DEP.EQUIPO DE TRANSPORTE"],
            ['codigo' => "840-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "840-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "840-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "840-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "840-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "840-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "840-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "840-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "840-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "840-42-0-0",	'descripcion' =>  "REACAND.DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "840-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO OFNA.Y COMPUTO"],
            ['codigo' => "840-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "840-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "840-49-0-0",	'descripcion' =>  "BASES PARA CONCURSO"],
            ['codigo' => "840-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "840-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "840-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "840-53-0-0",	'descripcion' =>  "TRASLADO AUTOMOTRIZ"],
            ['codigo' => "840-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "840-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "840-56-0-0",	'descripcion' =>  "CAFETERIA"],
            ['codigo' => "840-57-0-0",	'descripcion' =>  "MULTAS Y PENALIZACIONES Y SANCIONES"],
            ['codigo' => "840-59-0-0",	'descripcion' =>  "UNIFORMES "],
            ['codigo' => "840-64-0-0",	'descripcion' =>  "SERVICOS A UNIDADES"],
            ['codigo' => "840-65-0-0",	'descripcion' =>  "RECARGOS"],
            ['codigo' => "840-66-0-0",	'descripcion' =>  "RENTA DE AUTOSYSTEM"],
            ['codigo' => "840-67-0-0",	'descripcion' =>  "EMPQUES Y ENVOLTURAS"],
            ['codigo' => "840-68-0-0",	'descripcion' =>  "LICENCIA SOFTWARE"],
            ['codigo' => "840-69-0-0",	'descripcion' =>  "OTROS DE SERVICIO"],
            ['codigo' => "840-70-0-0",	'descripcion' =>  "ASIMILADOS A SALARIO"],
            ['codigo' => "840-71-0-0",	'descripcion' =>  "UNIFORMES "],
            ['codigo' => "850-1-0-0",	 'descripcion' => "SUELDOS FUNCIONARIOS"],
            ['codigo' => "850-2-0-0",	 'descripcion' => "SUELDOS Y SALARIOS"],
            ['codigo' => "850-3-0-0",	 'descripcion' => "COMISIONES EMPLEADOS"],
            ['codigo' => "850-4-0-0",	 'descripcion' => "VACACIONES Y PRIMA VACACIONAL"],
            ['codigo' => "850-5-0-0",	 'descripcion' => "GRATIFICACIONES Y COMPENSACIONES"],
            ['codigo' => "850-6-0-0",	 'descripcion' => "AGUINALDOS"],
            ['codigo' => "850-7-0-0",	 'descripcion' => "INDEMNIZACION Y PRIMA DE ANTIGUEDAD"],
            ['codigo' => "850-8-0-0",	 'descripcion' => "PREVISION SOCIAL"],
            ['codigo' => "850-9-0-0",	 'descripcion' => "GASTOS DE FIN DE AÑO"],
            ['codigo' => "850-10-0-0",	'descripcion' =>  "CREDITO AL SALARIO"],
            ['codigo' => "850-11-0-0",	'descripcion' =>  "IMPUESTO SUSTITUTIVO"],
            ['codigo' => "850-12-0-0",	'descripcion' =>  "2% SOBRE NOMINAS"],
            ['codigo' => "850-13-0-0",	'descripcion' =>  "5% I.N.F.O.N.A.V.I.T."],
            ['codigo' => "850-14-0-0",	'descripcion' =>  "I.M.S.S."],
            ['codigo' => "850-15-0-0",	'descripcion' =>  "S.A.R."],
            ['codigo' => "850-16-0-0",	'descripcion' =>  "PAPELERIA Y ARTICULOS DE ESCRITORIO"],
            ['codigo' => "850-17-0-0",	'descripcion' =>  "GASTOS DE VIAJE Y REPRESENTACION"],
            ['codigo' => "850-18-0-0",	'descripcion' =>  "PUBLICIDAD Y PROMOCION"],
            ['codigo' => "850-19-0-0",	'descripcion' =>  "CURSOS DE CAPACITACION"],
            ['codigo' => "850-20-0-0",	'descripcion' =>  "SERVICIOS PROFESIONALES"],
            ['codigo' => "850-21-0-0",	'descripcion' =>  "COMISIONES INDEPENDIENTES"],
            ['codigo' => "850-22-0-0",	'descripcion' =>  "MANTENIMIENTO DE EQUIPO DE TRANSPORTE"],
            ['codigo' => "850-23-0-0",	'descripcion' =>  "MANTENIMIENTO EDIFICIO Y EQUIPO"],
            ['codigo' => "850-24-0-0",	'descripcion' =>  "TELEFONO TELEGRAFO Y CORREO"],
            ['codigo' => "850-25-0-0",	'descripcion' =>  "LUZ, AGUA E IMPUESTO PREDIAL"],
            ['codigo' => "850-26-0-0",	'descripcion' =>  "IMPUESTOS Y DERECHOS LOCALES"],
            ['codigo' => "850-27-0-0",	'descripcion' =>  "ARRENDAMIENTO DE INMUEBLE"],
            ['codigo' => "850-28-0-0",	'descripcion' =>  "ARRENDAMIENTO DE MUEBLES"],
            ['codigo' => "850-29-0-0",	'descripcion' =>  "DEPRECIACION DE EDIFICIO"],
            ['codigo' => "850-30-0-0",	'descripcion' =>  "DEPRECIACION DE MAQ. Y EQ. DE TALLER"],
            ['codigo' => "850-31-0-0",	'descripcion' =>  "DEP. EQUIPO DE TRANSPORTE"],
            ['codigo' => "850-32-0-0",	'descripcion' =>  "DEPRECIACION MUEBLES Y ENSERES"],
            ['codigo' => "850-33-0-0",	'descripcion' =>  "DEPRECIACION EQUIPO DE COMPUTO"],
            ['codigo' => "850-34-0-0",	'descripcion' =>  "AMORTIZACIONES"],
            ['codigo' => "850-35-0-0",	'descripcion' =>  "SEGUROS Y FIANZAS"],
            ['codigo' => "850-36-0-0",	'descripcion' =>  "FLETES, EMBARQUES Y ACARREOS"],
            ['codigo' => "850-37-0-0",	'descripcion' =>  "CUOTAS Y SUSCRIPCIONES"],
            ['codigo' => "850-38-0-0",	'descripcion' =>  "NO DEDUCIBLES"],
            ['codigo' => "850-39-0-0",	'descripcion' =>  "COMISIONES BANCARIAS"],
            ['codigo' => "850-41-0-0",	'descripcion' =>  "CUENTAS INCOBRABLES"],
            ['codigo' => "850-42-0-0",	'descripcion' =>  "REACOND. DE UNIDADES Y/O PREENTREGAS"],
            ['codigo' => "850-44-0-0",	'descripcion' =>  "MANTENIMIENTO EQUIPO DE OFNA Y COMPUTO"],
            ['codigo' => "850-47-0-0",	'descripcion' =>  "VIGILANCIA"],
            ['codigo' => "850-48-0-0",	'descripcion' =>  "ASEO Y LIMPIEZA"],
            ['codigo' => "850-49-0-0",	'descripcion' =>  "BASES PARA CONCURSOS"],
            ['codigo' => "850-50-0-0",	'descripcion' =>  "CUOTAS SINDICALES"],
            ['codigo' => "850-51-0-0",	'descripcion' =>  "DONATIVOS"],
            ['codigo' => "850-52-0-0",	'descripcion' =>  "DIVERSOS"],
            ['codigo' => "850-53-0-0",	'descripcion' =>  "TRASLADOS AUTOMOTRIZ"],
            ['codigo' => "850-54-0-0",	'descripcion' =>  "COMBUSTIBLES Y LUBRICANTES"],
            ['codigo' => "850-55-0-0",	'descripcion' =>  "FONDO DE AHORRO"],
            ['codigo' => "850-57-0-0",	'descripcion' =>  "MEDIACION MERCANTIL"],
            ['codigo' => "850-58-0-0",	'descripcion' =>  "PRIMA DOMINICAL"],
            ['codigo' => "850-59-0-0",	'descripcion' =>  "SEPTIMO DIA"],
            ['codigo' => "850-60-0-0",	'descripcion' =>  "DIA FESTIVO"],
            ['codigo' => "850-61-0-0",	'descripcion' =>  "HORAS EXTRAS"],
            ['codigo' => "850-62-0-0",	'descripcion' =>  "MULTAS Y PENALIZACIONES"],
            ['codigo' => "850-63-0-0",	'descripcion' =>  "GESTORIAS Y PERMISOS"],
            ['codigo' => "850-64-0-0",	'descripcion' =>  "SERVICIOS A UNIDADES"],
            ['codigo' => "850-66-0-0",	'descripcion' =>  "RENTA DE AUTOSYSTEM"],
            ['codigo' => "850-68-0-0",	'descripcion' =>  "VERIFICACIONES"],
        ]);
    }
}
